app/home/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @File    : forms.py
# @author  : Jaxon
# @software: PyCharm
# @datetime: 9/26 026 下午 07:34

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from app.models import User
from flask import session


class RegistForm(FlaskForm):
    """会员注册表单"""
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={  # 附加选项
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
            "autofocus": ""
            # "required": "required"  # 添加强制属性，H5会在前端验证
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！"
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号码！"),
            Regexp("^1[3|4|5|7|8][0-9]{9}$", message="手机号码格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码！"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！"
        }
    )
    re_pwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请再次输入密码！"),
            EqualTo('pwd', message="两次密码输入不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请再次输入密码！"
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    # 昵称验证
    def validate_name(self, field):
        name = field.data
        if User.query.filter_by(name=name).count() == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self, field):
        email = field.data
        if User.query.filter_by(email=email).count() == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        if User.query.filter_by(phone=phone).count() == 1:
            raise ValidationError("手机号码已经存在！")


class LoginForm(FlaskForm):
    """会员登录表单"""
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
            "autofocus": ""
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！"
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-primary btn-block"
        }
    )

    # 账号验证
    def validate_name(self, field):
        name = field.data
        if User.query.filter_by(name=name).count() == 0:
            raise ValidationError("账号不存在！")


class UserdetailForm(FlaskForm):
    """会员中心表单"""
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入昵称！"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！"
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号码！"),
            Regexp("^1[3|4|5|7|8][0-9]{9}$", message="手机号码格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号码！"
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像！")
        ],
        description="头像",
        render_kw={
            "id": "input_face"
        }
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 10,
            "autofocus": ""
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success"
        }
    )

    def validate_name(self, field):
        if User.query.filter_by(name=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).name != field.data:
                raise ValidationError("名称已经存在！")

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).email != field.data:
                raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        if User.query.filter_by(phone=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).phone != field.data:
                raise ValidationError("手机号码已经存在！")


class PwdForm(FlaskForm):
    """修改密码"""
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码！",
            "autofocus": ""
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！"
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            "class": "btn btn-success"
        }
    )

    # 旧密码验证
    def validate_old_pwd(self, field):
        from flask import session
        old_pwd = field.data
        name = session["user"]
        user = User.query.filter_by(name=name).first()
        if not user.check_pwd(old_pwd):
            raise ValidationError("旧密码错误！")


class CommentForm(FlaskForm):
    """评论表单"""
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入内容！")
        ],
        description="内容",
        render_kw={
            "id": "input_content",
            "autofocus": ""
        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

app/home/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @File    : __init__.py
# @author  : Jaxon
# @software: PyCharm
# @datetime: 9/26 026 下午 07:32


from flask import Blueprint

# 定义蓝图
home = Blueprint("home", __name__)
import app.home.views

app/home/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @File    : views.py
# @author  : Jaxon
# @software: PyCharm
# @datetime: 9/26 026 下午 07:34


from app import db, app
from app.home import home
from app.home.forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm
from app.models import User, Userlog, Preview, Tag, Movie, Comment, Moviecol
from flask import render_template, redirect, url_for, flash, session, request, abort
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from functools import wraps
import uuid, os, datetime


# 定义登录判断装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # session不存在时请求登录
        if "user" not in session:
            return redirect(url_for("home.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)  # 对名字进行前后缀分离
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + "_" + uuid.uuid4().hex + fileinfo[-1]  # 生成新文件名
    return filename


# 定义首页列表视图
@home.route("/")
def index():
    tags = Tag.query.all()
    # 通过url获取参数
    tid = request.args.get("tid", '')
    star = request.args.get("star", '')
    time = request.args.get("time", '')
    pm = request.args.get("pm", '')
    cm = request.args.get("cm", '')
    pg = request.args.get("pg", '')

    # 保存获取的参数
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )

    # 根据获取的参数查询数据
    page_data = Movie.query
    if tid.isdigit() and tid is not None:
        page_data = page_data.filter_by(tag_id=int(tid))
    if star.isdigit() and star is not None:
        page_data = page_data.filter_by(star=int(star))
    if time.isdigit() and time is not None:
        page_data = page_data.order_by(
            Movie.addtime.desc() if int(time) == 1 else Movie.addtime.asc()
        )
    if pm.isdigit() and pm is not None:
        page_data = page_data.order_by(
            Movie.playnum.desc() if int(pm) == 1 else Movie.playnum.asc()
        )
    if cm.isdigit() and cm is not None:
        page_data = page_data.order_by(
            Movie.commentnum.desc() if int(cm) == 1 else Movie.commentnum.asc()
        )

    # 分页处理
    pages = page_data.count() // app.config['PAGE_SET'] if page_data.count() % app.config[
        'PAGE_SET'] == 0 else page_data.count() // app.config['PAGE_SET'] + 1
    page = int(pg) if pg.isdigit() and pg is not None and int(pg) <= pages else 1
    page_data = page_data.paginate(page=page, per_page=app.config['PAGE_SET'])

    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)


# 定义上映预告视图（首页动画）
@home.route("/animation/")
def animation():
    data = Preview.query.all()
    return render_template("home/animation.html", data=data)


# 定义电影搜索视图
@home.route("/search/")
def search():
    key = request.args.get("key", '')
    pg = request.args.get("pg", '')

    if key == '':
        abort(404)

    p = dict(key=key)

    # 模糊匹配
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).order_by(
        Movie.playnum.desc()
    )

    pages = page_data.count() // app.config['PAGE_SET'] if page_data.count() % app.config[
        'PAGE_SET'] == 0 else page_data.count() // app.config['PAGE_SET'] + 1
    page = int(pg) if pg.isdigit() and pg is not None and int(pg) <= pages else 1
    page_data = page_data.paginate(page=page, per_page=app.config['PAGE_SET'])

    return render_template("home/search.html", p=p, page_data=page_data)


# 定义电影详情视图
@home.route("/play/", methods=["GET", "POST"])
def play():
    form = CommentForm()
    mv = request.args.get("mv", '')
    pg = request.args.get("pg", '')

    p = dict(mv=mv)

    if not mv.isdigit() or mv is None:
        abort(404)

    movie = Movie.query.get_or_404(int(mv))
    # 提交评论
    if form.validate_on_submit():
        comment = Comment(
            content=form.data["content"],
            movie_id=int(mv),
            user_id=session["user_id"]
        )
        movie.commentnum += 1  # 增加评论数量
        db.session.add(comment)
        db.session.add(movie)
        db.session.commit()
        flash("评论提交成功！", "ok")

    # 增加播放数量
    movie.playnum += 1
    db.session.add(movie)
    db.session.commit()

    # 查询电影信息用于网页显示
    movie = Movie.query.join(Tag).filter(
        Movie.id == int(mv),
        Movie.tag_id == Tag.id
    ).first_or_404()

    # 查询评论数据
    page_data = Comment.query.join(User).filter(
        Comment.movie_id == int(mv),
        Comment.user_id == User.id
    ).order_by(
        Comment.addtime.desc()
    )
    # 分页显示
    pages = page_data.count() // app.config['PAGE_SET'] if page_data.count() % app.config[
        'PAGE_SET'] == 0 else page_data.count() // app.config['PAGE_SET'] + 1
    page = int(pg) if pg.isdigit() and pg is not None and int(pg) <= pages else 1
    page_data = page_data.paginate(page=page, per_page=app.config['PAGE_SET'])

    return render_template("home/play.html", p=p, form=form, movie=movie, page_data=page_data)


# 定义注册视图
@home.route("/regist/", methods=["GET", "POST"])
def regist():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            pwd=generate_password_hash(data["pwd"]),
            email=data["email"],
            phone=data["phone"],
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功，请登录！", "ok")
        return redirect(url_for("home.login"))
    return render_template("home/regist.html", form=form)


# 定义登录视图
@home.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()  # 导入登录表单
    if form.validate_on_submit():  # 验证是否有提交表单
        data = form.data
        user = User.query.filter_by(name=data["name"]).first()
        if not user.check_pwd(data["pwd"]):
            flash("密码错误！", "err")
            return redirect(url_for("home.login"))
        session["user"] = data["name"]
        session["user_id"] = user.id
        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(request.args.get("next") or url_for("home.user"))
    return render_template("home/login.html", form=form)


# 定义登出视图
@home.route("/logout/")
@user_login_req
def logout():
    session.pop("user")
    session.pop("user_id")
    return redirect(url_for("home.login"))


# 定义会员中心视图
@home.route("/user/", methods=["GET", "POST"])
@user_login_req
def user():
    form = UserdetailForm()
    user = User.query.get(int(session["user_id"]))
    if user.face is not None:
        form.face.validators = []
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data

        if not os.path.exists(app.config['UP_DIR'] + "users" + os.sep):
            os.makedirs(app.config['UP_DIR'] + "users" + os.sep)
            os.chmod(app.config['UP_DIR'] + "users" + os.sep, "rw")

        if form.face.data.filename != '':
            old_face = user.face
            file_face = secure_filename(form.face.data.filename)
            user.face = change_filename(file_face)
            form.face.data.save(app.config['UP_DIR'] + "users" + os.sep + user.face)
            if old_face is not None and os.path.exists(app.config['UP_DIR'] + "users" + os.sep + old_face):
                os.remove(app.config['UP_DIR'] + "users" + os.sep + old_face)

        user.name = data["name"]
        user.email = data["email"]
        user.phone = data["phone"]
        user.info = data["info"]
        db.session.add(user)
        db.session.commit()
        flash("修改成功！", "ok")
    return render_template("home/user.html", form=form, user=user)


# 定义修改密码视图
@home.route("/pwd/", methods=["GET", "POST"])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session["user"]).first()
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html", form=form)


# 定义评论记录视图
@home.route("/comments/")
@user_login_req
def comments():
    pg = request.args.get("pg", '')

    # 查询评论数据
    page_data = Comment.query.join(User).join(Movie).filter(
        Comment.user_id == session["user_id"],
        Comment.user_id == User.id,
        Comment.movie_id == Movie.id
    ).order_by(
        Comment.addtime.desc()
    )
    # 分页显示
    pages = page_data.count() // app.config['PAGE_SET'] if page_data.count() % app.config[
        'PAGE_SET'] == 0 else page_data.count() // app.config['PAGE_SET'] + 1
    page = int(pg) if pg.isdigit() and pg is not None and int(pg) <= pages else 1
    page_data = page_data.paginate(page=page, per_page=app.config['PAGE_SET'])
    return render_template("home/comments.html", page_data=page_data)


# 定义登录日志视图
@home.route("/loginlog/", methods=["GET"])
@user_login_req
def loginlog():
    userlog = Userlog.query.filter_by(
        user_id=session["user_id"]
    ).order_by(
        Userlog.addtime.desc()
    ).limit(15).all()
    return render_template("home/loginlog.html", userlog=userlog)


# 定义添加收藏视图
@home.route("/moviecol/add/", methods=["GET"])
@user_login_req
def moviecol_add():
    uid = request.args.get("uid", '')
    mid = request.args.get("mid", '')
    if not uid.isdigit() or uid is None or not mid.isdigit() or mid is None:
        abort(404)
    moviecol = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if moviecol == 1:
        data = dict(ok=0)
    elif moviecol == 0:

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input id="key_movie" type="text" class="form-control" {% if p %}value="{{ p['key'] }}" {% endif %}
                           placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a id="do_search" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if "user" not in session %}
                <li>
                    <a class="curlink" href="{{ url_for('home.regist') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                {% else %}
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content_cus %}
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
        // 禁用回车键
        $(this).keydown(function (e) {
            var key = window.event ? e.keyCode : e.which;
            if (key.toString() == "13") {
                return false;
            }
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            if ($.trim(key).length != 0) {
                location.href = "{{ url_for('home.search') }}?key=" + key;
            }
        });
    })
</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/index.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg %}

{% block content_cus %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                        src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for v in tags %}
                            <a href="{{ url_for('home.index') }}?tid={{ v.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{ v.name }}</a>
                            &nbsp;
                            {% endfor %}
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for v in range(1, 6) %}
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ v }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ v }}星</a>
                            &nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}"
                               class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}"
                               class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1"
                               class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2"
                               class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <a href="{{ url_for('home.play') }}?mv={{ v.id }}">
                        <img src="{{ url_for('static', filename='uploads/'+v.logo) }}"
                             class="img-responsive center-block"
                             alt="">
                    </a>
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                        <div>
                            {% for var in range(v.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                            {% for var in range(5-v.star) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{{ url_for('home.play') }}?mv={{ v.id }}" class="btn btn-primary" role="button"><span
                            class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    {{ pg.page(page_data,
                    url_for('home.index')+'?tid='+p['tid']+'&star='+p['star']+'&time='+p['time']+'&pm='+p['pm']+'&cm='+p['cm']+'&')
                    }}
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}